### ISSUE TITLE
API >=26 problem is fix

### ISSUE THREAD

**Issue by ahmetozel** [mathias5r/rn-heartbeat#9]
### API >=26 problem is fix

`package com.rnheartbeat;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.os.Build;

public class BootUpReceiver extends BroadcastReceiver {

    @Override
    public void onReceive(Context context, Intent intent) {
        if(intent.getAction() == Intent.ACTION_BOOT_COMPLETED){
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                //log("Starting the service in >=26 Mode from a BroadcastReceiver")
                context.startForegroundService(new Intent(context, HeartbeartService.class));
                return;
            }
            //log("Starting the service in < 26 Mode from a BroadcastReceiver")
            context.startService(new Intent(context, HeartbeartService.class));
        }

    }
}
`

**Comment by dksami** [comment]
This still does not work. I have tried using it with api support of 28 and it fails. any clue ?

**Comment by ahmetozel** [comment]
@dksami  Probably, there's a point you missed.
İf you send message to me, I can help you real time.
ahmet.ozel.67300@gmail.com

**Comment by dksami** [comment]
You go on and check.

**Comment by dksami** [comment]
FIXED <3

**Comment by lyseiha** [comment]
how?

**Comment by Raja0sama** [comment]
> how?

You need a foreground Service? https://www.npmjs.com/package/@supersami/react-native-foreground-service

**Comment by lyseiha** [comment]
Did you run on oppo F5 android 8.1.0? after run and kill app foreground service also gone.

**Comment by Raja0sama** [comment]
> Did you run on oppo F5 android 8.1.0? after run and kill app foreground service also gone.

Yes it is going to work on that as well.

**Comment by lyseiha** [comment]
I tried the rn-hearbeat on the oppo f5 android 8.1.0 after app killed the foreground also gone.
